spring:
  application:
    name: insurance-policy-manager

  # Database Configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:insurance_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA/Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true